[package]
name = "green-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
green-lib = { git = "https://github.com/urlordjames/green-lib.git", version = "0.1" }
serde_json = "1"
sha2 = "0.10"
clap = { version = "3.2", features = [ "derive" ] }
url = "2.2"

[profile.release]
lto = "fat"